# Generated by Django 5.2.3 on 2025-09-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('russian', models.CharField(max_length=255)),
                ('turkmen', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_tm', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['english'],
            },
        ),
    ]
